config/routes.rb
Rails.application.routes.draw do
root 'pages#home'
get 'about', to: 'pages#about' 
resources :articles#, only: [:show, :index, :new, :create, :edit, :update, :destroy]


end

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # Adding a root route.  Want to send to Controller.
  # root 'application#hello'  
  # Once we write root application, we want a method to handle this request. So then we put the # after application (controller), followed by # followed by method name. This is telling rails to expect a hello method in the application_controller.rb file.
  # Above was specifying.  We want to use Rails convention.
# root 'pages#home'
# As of now these do not exist and error that is there is : uninitialized constant PagesController.   We need to open terminal and generate controller. command is "rails generate controller pages" This will create a pages_controller and in views, pages.

# If we refresh our page, the error is The action 'home' could not be found for PagesController.
# So we need to do that in our <pages_controller.
# Adding an about page. -- Right now there is no about page.  We get a GET error. So first step is we add this route. So add the command get about.  
# Once this is done we add where to send it to. Controller#Action
# Now error is The action 'about' could not be found for PagesController.  So now go to app>> Controllers.

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 4, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 30000}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Coming from routes here.  Need to specify the method. Where we want the request to be sent.  If we do nothing here, error that comes is The action 'hello' could not be found for ApplicationController.
    # def hello
    # end
    # Now if I refresh my localhost:3000, error is: No template for interactive request -- ApplicationController#hello is missing a template for request formats: text/html.  So we need to add text/html. So we need to add a template.  We can do that directly
    # def hello
    #     render html: 'Hello World! This is the home page'
    # end  
    # We will use Rails convention. Views.
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was successfully created"
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private
    
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    (params.require(:article).permit(:title, :description))
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about
    end
    # Coming here from routes. After we created the pages controller.  Error Was "The action 'home' could not be found for PagesController". Now the error that comes is
    # No template for interactive request ------PagesController#home is missing a template for request formats: text/html.  So next step is to create that. We right click on pages and create home.html.erb page.
    #  For about..right now we do not have a def about. error is The action 'about' could not be found for PagesController.  So we do that.
    # Now if we refresh - error is No template for interactive request --- PagesController#about is missing a template for request formats: text/html. So we create the page. Go to views, >> pages and create a page 'about'
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>The following errors prevented your article from being saved</h2>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
   <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<%= form_with(model: @article, local: true) do |f| %>

<p>
  <%= f.label :title %><br/>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :description %><br/>
  <%= f.text_area :description %>

</p>

<p>
  <%= f.submit %>
</p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Cancel edit and return to articles listing', articles_path %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article_path(article) %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "are you sure?"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<p> 
  <%= link_to 'Create new article', new_article_path %> |
  <%= link_to 'Home', root_path %> 
</p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<%= link_to 'Return to articles listing', articles_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description%></p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "are you sure?"} %> |
<%= link_to 'Return to articles listing', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
  <%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> About this site </h1>

<p>This is the first site I have created with Ruby on Rails. It allows you to create, edit, save, and delete articles. This was created from the ground up using Visual Studio Code, Ruby, and Rails. </p>
<%= link_to 'Home', root_path %> |
<%= link_to 'Articles listing', articles_path %>

app/views/pages/home.html.erb
<h1> Welcome to Parker's first web app! </h1>

<%= link_to 'About this site', about_path %> |
<%= link_to 'Articles listing', articles_path %>